### PR TITLE
Convert CB into library

### PR DESCRIPTION
**Pull request by jpolchlo**
To perhaps improve the utility of this project, I've broken it up into library code and separate executables.  The main difference between the library code and the original scripts is that some intermediate structures are not written to disk, but instead returned directly.  The executable wrappers handle the writing out to file instead.  I've also attempted to allow the local scratch space to be chosen by the user rather than assuming `/tmp`—useful in space-constrained environments where scratch space may be mounted elsewhere.

The library is now pip-installable as well.

#### Notes

There are many smaller, undocumented scripts that were placed in `/bin` which might need to be relocated.  I'd love some guidance as to where to put those.

Complete testing of meta-gather and meta-merge needs to be done to ensure that things work well with `download_run.sh`.

### CODE REVIEW

**Comment by jamesmcclain** [comment]
Thank you, this looks impressive.

Do the scripts `meta-gather` and `meta-merge` still work?

**Comment by jpolchlo** [comment]
I've not tested the meta functions.  Can you give me a sequence of commands that should work, and I'll run them to make sure?  I was mostly concentrated on the library functions.

**Comment by jamesmcclain** [comment]
> I've not tested the meta functions. Can you give me a sequence of commands that should work, and I'll run them to make sure? I was mostly concentrated on the library functions.

I don't want to hold up progress, but I found in development that being able to easily run locally and on batch with zero setup was helpful.

**Comment by jpolchlo** [comment]
Read you loud and clear.  Will test and report back.

**Comment by jamesmcclain** [comment]
It might be possible to programatically install the new dependency (http://jelly.codes/articles/python-pip-module/) if it is found to be missing (in the `merge` script, the `gather` scripts, and any other affected scripts).

**Comment by jamesmcclain** [comment]
@jpolchlo regarding the geojson that produces empty filtered results: it appears that the total area there is small compared to the default amount of uncovered area (the `max_uncovered` argument to response).  Reducing `max_uncovered` to something that is small relative to the area of the input should solve the problem.

**Comment by jpolchlo** [comment]
Thanks for the tip.  I'll look into it.

Also, this PR is ready for another look, I think.

**Pull request merged**
